spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create-drop
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.jackson.json.datetime.write-dates-as-timestamps=false
info.app.name=Container Resource Monitor
info.app.version=1.0.0